// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUHfeUIQ4JbkVabLwTkr2Lh9tgssFsfgE',
    appId: '1:39738731594:web:2ced338e20ae030d6c8ab3',
    messagingSenderId: '39738731594',
    projectId: 'taxibooking-8e37c',
    authDomain: 'taxibooking-8e37c.firebaseapp.com',
    storageBucket: 'taxibooking-8e37c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBccjmpfd3N3SuBpOh41pXSg-DtQZCcwIU',
    appId: '1:39738731594:android:1c6d70aab0cdf5966c8ab3',
    messagingSenderId: '39738731594',
    projectId: 'taxibooking-8e37c',
    storageBucket: 'taxibooking-8e37c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDrsHeTBGl9u9vUVJoH0ruk7S8vISFYR8',
    appId: '1:39738731594:ios:4a4458c70489b51b6c8ab3',
    messagingSenderId: '39738731594',
    projectId: 'taxibooking-8e37c',
    storageBucket: 'taxibooking-8e37c.firebasestorage.app',
    iosBundleId: 'com.example.pickup',
  );
}
